import type { Metadata } from "next";
import Link from "next/link";
import { Figure, GuideByline, MethodologyNote, Scenario, GUIDE_SVG } from "@/components/GuideChrome";
import { ComparisonTable, Callout } from "@/components/GuideComponents";
export const metadata: Metadata = { title: "How much does it cost to install flooring? (2026 prices)", description: "LVP: $3-10/ft². Hardwood: $8-16/ft². Tile: $7-20/ft². Material is half the bill — labor is the other half. Full breakdown by type.", alternates: { canonical: "/cost-to-install-flooring" } };
function MaterialCostSVG() { const mats=[{label:"LVP / laminate",low:3,high:10,color:GUIDE_SVG.slate},{label:"Engineered hardwood",low:6,high:14,color:GUIDE_SVG.inkMuted},{label:"Solid hardwood",low:8,high:16,color:"#8B6B3D"},{label:"Porcelain tile",low:7,high:20,color:GUIDE_SVG.accent},{label:"Natural stone",low:12,high:35,color:GUIDE_SVG.accent}]; return (<svg viewBox="0 0 680 220" width="100%" height="auto" role="img" aria-label="Flooring cost per sq ft installed: LVP $3-10, hardwood $8-16, tile $7-20."><text x="20" y="26" fontSize="13" fontWeight="600" fill={GUIDE_SVG.ink}>Installed cost per square foot by material (2026)</text><text x="20" y="43" fontSize="10" fill={GUIDE_SVG.inkFaint}>Includes material, underlayment, adhesive/mortar, transitions, and labor</text>{mats.map((m,i)=>{const y=65+i*30;const xS=210+m.low*8;const w=(m.high-m.low)*8;return(<g key={m.label}><text x="200" y={y+14} textAnchor="end" fontSize="11" fontWeight="600" fill={GUIDE_SVG.ink}>{m.label}</text><rect x={xS} y={y} width={w} height="20" rx="3" fill={m.color} opacity="0.6"/><text x={xS-5} y={y+14} textAnchor="end" fontSize="10" fill={GUIDE_SVG.inkFaint}>${m.low}</text><text x={xS+w+5} y={y+14} fontSize="10" fill={GUIDE_SVG.inkFaint}>${m.high}/ft²</text></g>)})}</svg>); }
function LaborVsMaterialSVG() { return (<svg viewBox="0 0 680 120" width="100%" height="auto" role="img" aria-label="Labor is 40-60% of flooring cost. Material is 40-60%."><text x="20" y="26" fontSize="13" fontWeight="600" fill={GUIDE_SVG.ink}>The material is only half the bill</text>{[{label:"LVP click-lock",matPct:55,labPct:45},{label:"Hardwood nail-down",matPct:45,labPct:55},{label:"Tile (mortar + grout)",matPct:40,labPct:60}].map((f,i)=>{const y=55+i*22;return(<g key={f.label}><text x="180" y={y+12} textAnchor="end" fontSize="10" fontWeight="600" fill={GUIDE_SVG.ink}>{f.label}</text><rect x="190" y={y} width={f.matPct*2.5} height="14" rx="2" fill={GUIDE_SVG.accent} opacity="0.6"/><rect x={190+f.matPct*2.5} y={y} width={f.labPct*2.5} height="14" rx="2" fill={GUIDE_SVG.slate} opacity="0.6"/><text x={195+f.matPct*2.5+f.labPct*2.5} y={y+12} fontSize="9" fill={GUIDE_SVG.inkFaint}>Mat {f.matPct}% · Lab {f.labPct}%</text></g>)})}</svg>); }
function RoomCostSVG() { const rooms=[{room:"Bedroom (150 ft²)",lvp:"$600–1,200",hw:"$1,200–2,400",tile:"$1,200–2,600"},{room:"Living room (300 ft²)",lvp:"$1,200–2,400",hw:"$2,400–4,800",tile:"$2,400–5,200"},{room:"Whole house (1,500 ft²)",lvp:"$5,000–12,000",hw:"$12,000–24,000",tile:"$12,000–26,000"}]; const hY=65;const rH=28; return (<svg viewBox="0 0 680 180" width="100%" height="auto" role="img" aria-label="Flooring cost by room: bedroom $600-2,600, whole house $5,000-26,000."><text x="20" y="26" fontSize="13" fontWeight="600" fill={GUIDE_SVG.ink}>Total installed cost by room and material</text><rect x="30" y={hY-18} width="620" height="26" rx="4" fill={GUIDE_SVG.bgWarm}/>{[{l:"Room",x:120},{l:"LVP",x:300},{l:"Hardwood",x:430},{l:"Tile",x:560}].map(h=>(<text key={h.l} x={h.x} y={hY-2} textAnchor="middle" fontSize="10" fontWeight="700" fill={GUIDE_SVG.inkMuted}>{h.l}</text>))}{rooms.map((r,i)=>{const y=hY+10+i*rH;return(<g key={r.room}>{i%2===0&&<rect x="30" y={y-4} width="620" height={rH} fill={GUIDE_SVG.bgWarm} opacity="0.4"/>}<text x="120" y={y+14} textAnchor="middle" fontSize="10" fontWeight="600" fill={GUIDE_SVG.ink}>{r.room}</text><text x="300" y={y+14} textAnchor="middle" fontSize="10" fill={GUIDE_SVG.accent} fontWeight="600">{r.lvp}</text><text x="430" y={y+14} textAnchor="middle" fontSize="10" fill={GUIDE_SVG.inkMuted}>{r.hw}</text><text x="560" y={y+14} textAnchor="middle" fontSize="10" fill={GUIDE_SVG.inkFaint}>{r.tile}</text></g>)})}</svg>); }
function RemovalCostSVG() { return (<svg viewBox="0 0 680 120" width="100%" height="auto" role="img" aria-label="Old flooring removal: carpet $1-2/ft², tile $3-6/ft², hardwood $2-4/ft²."><text x="20" y="26" fontSize="13" fontWeight="600" fill={GUIDE_SVG.ink}>Old flooring removal cost (often not in the estimate)</text>{[{type:"Carpet",cost:"$1–2/ft²",note:"Easiest — DIY in 2 hours",y:55},{type:"Tile/stone",cost:"$3–6/ft²",note:"Hardest — mortar bed must come up too",y:80},{type:"Hardwood",cost:"$2–4/ft²",note:"Nailed boards take longer than glued LVP",y:105}].map(r=>(<g key={r.type}><text x="110" y={r.y+10} textAnchor="end" fontSize="11" fontWeight="700" fill={GUIDE_SVG.ink}>{r.type}</text><text x="120" y={r.y+4} fontSize="10" fill={GUIDE_SVG.accent} fontWeight="600">{r.cost}</text><text x="120" y={r.y+20} fontSize="9" fill={GUIDE_SVG.inkFaint}>{r.note}</text></g>))}</svg>); }
export default function CostToInstallFlooring() { return (<article>
  <section className="container-wide pt-6 md:pt-8"><div className="bg-bg-warm rounded-xl p-8 md:p-10"><nav aria-label="Breadcrumb" className="text-[11px] uppercase tracking-[0.08em] text-ink-faint mb-3 font-semibold"><Link href="/" className="text-accent hover:text-accent-hover transition-colors">Home</Link><span className="mx-2">·</span><span>Cost guides</span></nav><h1 className="text-3xl md:text-5xl font-bold tracking-tighter leading-[1.05] mb-3 text-ink">How much does it cost to install new flooring?</h1><p className="text-base md:text-lg text-ink-muted max-w-2xl leading-relaxed">Material is half the bill. Labor is the other half. LVP costs $3-10/ft² installed. Hardwood runs $8-16. Tile is $7-20. The range depends more on who installs it than what you buy.</p></div></section>
  <section className="container-content py-10 md:py-14"><div className="guide-prose">
    <GuideByline updated="April 20, 2026" reviewedAgainst="NWFA installation guidelines, Floor & Decor pricing, and contractor cost surveys" />
    <h2>The material is half the bill, and sometimes not even that</h2>
    <p>When a homeowner shops for flooring, they see the per-square-foot price on the box and multiply by room size. A 300 square foot living room in $4/ft² LVP looks like a $1,200 project. But installed, it is $1,800 to $2,400 because labor, underlayment, transitions, and old floor removal add 50 to 100 percent to the material cost. For tile, labor often exceeds the material cost because mortar work is slow and skilled. The <Link href="/flooring-calculator" className="text-accent hover:underline">flooring calculator</Link> gives you the material side; this page covers the full installed picture.</p>
    <Figure number={1} caption="LVP is the value leader. Solid hardwood and natural stone cost 3-5× more installed. The gap is mostly labor — skilled hardwood and tile installers charge $3-8/ft² in labor alone."><MaterialCostSVG /></Figure>
    <MethodologyNote><p>Pricing from Floor &amp; Decor, Home Depot, and Lowe&apos;s 2026 retail (materials) plus HomeGuide and Angi contractor surveys (labor). NWFA waste factors applied. Underlayment and adhesive included in installed costs.</p></MethodologyNote>
    <Figure number={2} caption="Tile has the highest labor ratio because mortar application, cutting, and grouting are slow skilled work. LVP click-lock is the most DIY-friendly and labor-light."><LaborVsMaterialSVG /></Figure>
    <h2>Total cost by room size</h2>
    <Figure number={3} caption="A whole-house LVP job runs $5,000-12,000. The same house in hardwood: $12,000-24,000. Material choice is the biggest single decision in the budget."><RoomCostSVG /></Figure>
    <Scenario location="Nashville, TN">A couple installed 1,200 ft² of LVP throughout their main floor. Material: $4.50/ft² ($5,400). Professional installation: $2.50/ft² ($3,000). Transitions and underlayment: $350. Old carpet removal (DIY): $0. Total: $8,750. A neighbor did the same area in engineered hardwood at $9/ft² material plus $4/ft² labor: $15,600. The LVP looks nearly identical to the hardwood from standing height and cost 44% less.</Scenario>
    <h2>Do not forget: removing the old floor</h2>
    <Figure number={4} caption="Old flooring removal is often quoted separately or not at all. Carpet is cheap to remove. Tile with mortar bed is the most expensive."><RemovalCostSVG /></Figure>
    <Callout label="LVP can go over existing flooring in many cases">LVP click-lock can be installed directly over existing vinyl, laminate, or hardwood if the surface is flat and in decent condition. This eliminates removal cost entirely and is one reason LVP dominates the renovation market. You cannot do this with tile or solid hardwood — both require the old floor to come up first.</Callout>
    <ComparisonTable columns={[{title:"DIY"},{title:"Professional"}]} rows={[{label:"Material (1,000 ft² LVP)",values:["$3,000–5,000","$3,000–5,000"]},{label:"Underlayment + transitions",values:["$200–400","Included"]},{label:"Old floor removal",values:["$0 (DIY carpet pull)","$500–1,500"]},{label:"Labor",values:["$0 (1–2 weekends)","$2,000–4,000"]},{label:"Total",values:[<strong key="d">$3,200–5,400</strong>,<strong key="p">$5,500–10,500</strong>]}]} caption="LVP click-lock is the most DIY-friendly flooring. Hardwood and tile should be hired out unless you have installation experience." />
    <p>For material quantities, use the <Link href="/flooring-calculator" className="text-accent hover:underline">flooring calculator</Link> (handles waste by material type). For tile-specific estimates including grout, use the <Link href="/tile-calculator" className="text-accent hover:underline">tile calculator</Link> and <Link href="/grout-calculator" className="text-accent hover:underline">grout calculator</Link>.</p>
  </div></section>
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({"@context":"https://schema.org","@type":"Article",headline:"How much does it cost to install flooring? (2026)",datePublished:"2026-04-13",dateModified:"2026-04-20",author:{"@type":"Person",name:"Ash K.",url:"https://www.tallyard.com/about"},publisher:{"@type":"Organization",name:"Tallyard",url:"https://www.tallyard.com"},mainEntityOfPage:"https://www.tallyard.com/cost-to-install-flooring"})}}/>
</article>); }
