import type { Metadata } from "next";
import Link from "next/link";
import { Figure, GuideByline, MethodologyNote, Scenario, GUIDE_SVG } from "@/components/GuideChrome";
import { ComparisonTable, Callout } from "@/components/GuideComponents";
export const metadata: Metadata = { title: "How much does it cost to install siding? (2026 prices)", description: "Vinyl: $6,000-16,000. Fiber cement: $12,000-26,000. Cedar: $16,000-32,000. 30-year TCO tells a different story than install price.", alternates: { canonical: "/cost-to-install-siding" } };
function MaterialSVG() { const mats=[{label:"Vinyl",low:3,high:8},{label:"Aluminum",low:4,high:8},{label:"Engineered wood (LP)",low:5,high:10},{label:"Fiber cement (Hardie)",low:6,high:13},{label:"Cedar/redwood",low:8,high:16}]; return (<svg viewBox="0 0 680 220" width="100%" height="auto" role="img" aria-label="Siding cost per sq ft: vinyl $3-8, fiber cement $6-13, cedar $8-16."><text x="20" y="26" fontSize="13" fontWeight="600" fill={GUIDE_SVG.ink}>Installed cost per square foot (2026)</text>{mats.map((m,i)=>{const y=60+i*30;const xS=200+m.low*15;const w=(m.high-m.low)*15;return(<g key={m.label}><text x="190" y={y+14} textAnchor="end" fontSize="11" fontWeight="600" fill={GUIDE_SVG.ink}>{m.label}</text><rect x={xS} y={y} width={w} height="20" rx="3" fill={i>=3?GUIDE_SVG.accent:GUIDE_SVG.slate} opacity="0.6"/><text x={xS-5} y={y+14} textAnchor="end" fontSize="10" fill={GUIDE_SVG.inkFaint}>${m.low}</text><text x={xS+w+5} y={y+14} fontSize="10" fill={GUIDE_SVG.inkFaint}>${m.high}/ft²</text></g>)})}</svg>); }
function TCOSVG() { const mats=[{label:"Vinyl",install:"$14,000",paint30yr:"$0",total30yr:"$14,000"},{label:"Fiber cement",install:"$24,000",paint30yr:"$9,000",total30yr:"$33,000"},{label:"Cedar",install:"$28,000",paint30yr:"$12,000",total30yr:"$40,000"}]; const hY=65;const rH=28; return (<svg viewBox="0 0 680 180" width="100%" height="auto" role="img" aria-label="30-year TCO: vinyl $14K, fiber cement $33K, cedar $40K including repainting."><text x="20" y="26" fontSize="13" fontWeight="600" fill={GUIDE_SVG.ink}>30-year total cost of ownership (2,000 ft² home)</text><rect x="40" y={hY-18} width="600" height="26" rx="4" fill={GUIDE_SVG.bgWarm}/>{[{l:"Material",x:140},{l:"Install",x:300},{l:"Repainting",x:430},{l:"30-yr total",x:570}].map(h=>(<text key={h.l} x={h.x} y={hY-2} textAnchor="middle" fontSize="10" fontWeight="700" fill={GUIDE_SVG.inkMuted}>{h.l}</text>))}{mats.map((m,i)=>{const y=hY+10+i*rH;return(<g key={m.label}>{i%2===0&&<rect x="40" y={y-4} width="600" height={rH} fill={GUIDE_SVG.bgWarm} opacity="0.4"/>}<text x="140" y={y+14} textAnchor="middle" fontSize="11" fontWeight="600" fill={GUIDE_SVG.ink}>{m.label}</text><text x="300" y={y+14} textAnchor="middle" fontSize="11" fill={GUIDE_SVG.inkMuted}>{m.install}</text><text x="430" y={y+14} textAnchor="middle" fontSize="11" fill={GUIDE_SVG.inkMuted}>{m.paint30yr}</text><text x="570" y={y+14} textAnchor="middle" fontSize="11" fill={GUIDE_SVG.accent} fontWeight="700">{m.total30yr}</text></g>)})}</svg>); }
function InsuranceSVG() { return (<svg viewBox="0 0 680 80" width="100%" height="auto" role="img" aria-label="Fiber cement has Class A fire rating. Some insurers offer 5-10% premium discounts for fire-rated cladding."><text x="20" y="26" fontSize="13" fontWeight="600" fill={GUIDE_SVG.ink}>The insurance angle</text><text x="20" y="55" fontSize="11" fill={GUIDE_SVG.inkMuted}>Fiber cement carries a Class A (1-hour) fire rating. Vinyl melts. Cedar has limited fire resistance.</text><text x="20" y="75" fontSize="10" fill={GUIDE_SVG.inkFaint}>Some insurers offer 5-10% premium discounts for homes with fire-rated cladding. Ask your agent.</text></svg>); }
export default function CostToInstallSiding() { return (<article>
  <section className="container-wide pt-6 md:pt-8"><div className="bg-bg-warm rounded-xl p-8 md:p-10"><nav aria-label="Breadcrumb" className="text-[11px] uppercase tracking-[0.08em] text-ink-faint mb-3 font-semibold"><Link href="/" className="text-accent hover:text-accent-hover transition-colors">Home</Link><span className="mx-2">·</span><span>Cost guides</span></nav><h1 className="text-3xl md:text-5xl font-bold tracking-tighter leading-[1.05] mb-3 text-ink">How much does it cost to install siding?</h1><p className="text-base md:text-lg text-ink-muted max-w-2xl leading-relaxed">Vinyl is cheapest to install. Fiber cement is cheapest over 30 years when you factor in zero maintenance vs two repaint cycles. The install price is not the real price.</p></div></section>
  <section className="container-content py-10 md:py-14"><div className="guide-prose">
    <GuideByline updated="April 20, 2026" reviewedAgainst="James Hardie, CertainTeed, LP SmartSide specs and contractor pricing" />
    <h2>Install price and ownership price are different numbers</h2>
    <p>Vinyl costs $14,000 to side a 2,000 square foot home and never needs painting. Fiber cement costs $24,000 and needs repainting at year 12 and year 24 ($4,500 each time). Cedar costs $28,000 and needs staining every 4 to 5 years ($2,000 to $3,000 per application). Over 30 years, the cheapest siding to install (vinyl at $14,000 total) costs less than half what the premium option (cedar at $40,000 total) costs. But fiber cement lasts 50 years and vinyl lasts 30, so the per-year cost tells yet another story.</p>
    <Figure number={1} caption="Per-foot installed cost ranges from $3 for vinyl to $16 for cedar. Fiber cement at $6-13 is the mid-market standard for new construction."><MaterialSVG /></Figure>
    <MethodologyNote><p>Install costs from James Hardie, CertainTeed, and LP SmartSide contractor pricing networks. Repaint costs from PCA (Painting Contractors of America) residential exterior surveys. All costs for a 2,000 ft² home with 2,200 ft² of wall area including gables.</p></MethodologyNote>
    <Figure number={2} caption="Vinyl has zero ongoing cost. Fiber cement needs two repaint cycles in 30 years. Cedar needs 6-7 stain cycles. The install price leader and the TCO leader are different materials."><TCOSVG /></Figure>
    <Scenario location="Charlotte, NC">A homeowner replacing cedar lap siding got two quotes. Option A: vinyl at $15,500. Option B: fiber cement (James Hardie) at $26,800. She picked fiber cement because her home insurance agent confirmed a 7% premium reduction for Class A fire-rated cladding, saving $180/year ($5,400 over 30 years). The net cost difference over 30 years: fiber cement cost $7,400 more to install but saved $5,400 in insurance and $12,000 in staining the cedar would have needed. Fiber cement won by $10,000 over the 30-year period.</Scenario>
    <Figure number={3} caption="Fire-rated siding can reduce insurance premiums. Vinyl and cedar do not qualify for fire rating discounts in most markets."><InsuranceSVG /></Figure>
    <ComparisonTable columns={[{title:"Vinyl"},{title:"Fiber cement"},{title:"Cedar"}]} rows={[{label:"Install (2,000 ft² home)",values:["$6,000–16,000","$12,000–26,000","$16,000–32,000"]},{label:"Fire rating",values:["None (melts)","Class A (1 hr)","Class C"]},{label:"Impact resistance",values:["Cracks in cold","Excellent","Good"]},{label:"DIY",values:["Moderate","Hard (heavy)","Moderate"]},{label:"Lifespan",values:["25–40 yr","30–50 yr","20–40 yr"]}]} caption="Fiber cement is the contractor default for new construction. Vinyl dominates budget and retrofit markets." />
    <p>For material quantity, use the <Link href="/siding-calculator" className="text-accent hover:underline">siding calculator</Link>. For a deep-dive on the vinyl vs Hardie decision, read the <Link href="/guides/vinyl-vs-fiber-cement-siding" className="text-accent hover:underline">vinyl vs fiber cement buying guide</Link>.</p>
  </div></section>
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({"@context":"https://schema.org","@type":"Article",headline:"How much does it cost to install siding? (2026)",datePublished:"2026-04-17",dateModified:"2026-04-20",author:{"@type":"Person",name:"Ash K.",url:"https://www.tallyard.com/about"},publisher:{"@type":"Organization",name:"Tallyard",url:"https://www.tallyard.com"},mainEntityOfPage:"https://www.tallyard.com/cost-to-install-siding"})}}/>
</article>); }
