import type { Metadata } from "next";
import Link from "next/link";
export const metadata: Metadata = { title: "Landscaping, deck, and fence calculators — Tallyard", description: "Calculators for deck, fence, paver, mulch, gravel, sod, topsoil, pool, and rainwater. Free tools for outdoor projects.", alternates: { canonical: "/calculators/landscaping" } };
const tools = [
  { slug: "deck-calculator", name: "Deck calculator", desc: "Decking, joists, posts, and footings by size and material." },
  { slug: "fence-calculator", name: "Fence calculator", desc: "Posts, rails, pickets, and concrete by linear footage." },
  { slug: "paver-calculator", name: "Paver calculator", desc: "Paver count, gravel base, sand, and edge restraint." },
  { slug: "mulch-calculator", name: "Mulch calculator", desc: "Cubic yards by area and depth. Bulk vs bag pricing." },
  { slug: "gravel-calculator", name: "Gravel calculator", desc: "Tons and cubic yards with compaction factor." },
  { slug: "topsoil-calculator", name: "Topsoil calculator", desc: "Cubic yards of screened or amended soil." },
  { slug: "sod-calculator", name: "Sod calculator", desc: "Pallets, rolls, or slabs by lawn area." },
  { slug: "pool-chlorine-calculator", name: "Pool chlorine calculator", desc: "Chlorine dose by pool volume and chemical type." },
  { slug: "rainwater-calculator", name: "Rainwater calculator", desc: "Collection capacity by roof area and rainfall." },
];
export default function LandscapingPillar() { return (<article>
  <section className="container-wide pt-6 md:pt-8"><div className="bg-bg-warm rounded-xl p-8 md:p-10">
    <nav aria-label="Breadcrumb" className="text-[11px] uppercase tracking-[0.08em] text-ink-faint mb-3 font-semibold"><Link href="/calculators" className="text-accent hover:text-accent-hover transition-colors">Calculators</Link><span className="mx-2">·</span><span>Landscaping</span></nav>
    <h1 className="text-3xl md:text-5xl font-bold tracking-tighter leading-[1.05] mb-3 text-ink">Landscaping, deck, and outdoor</h1>
    <p className="text-base md:text-lg text-ink-muted max-w-2xl leading-relaxed">Nine tools for everything outside the four walls. Decks, fences, patios, lawn, garden beds, pool maintenance, and rainwater.</p>
  </div></section>
  <section className="container-wide py-10"><div className="grid grid-cols-1 md:grid-cols-3 gap-5">{tools.map((t) => (<Link key={t.slug} href={`/${t.slug}`} className="block bg-surface border border-line rounded-lg p-6 hover:border-accent transition-colors group"><h2 className="text-base font-bold text-ink group-hover:text-accent transition-colors mb-2">{t.name}</h2><p className="text-sm text-ink-muted leading-relaxed">{t.desc}</p></Link>))}</div></section>
  <section className="container-content pb-16"><div className="guide-prose">
    <h2>Outdoor projects have one variable indoor projects do not: weather</h2>
    <p>Every outdoor calculator accounts for material exposure to rain, freeze-thaw, UV, and soil moisture. Fence posts in contact with soil rot from the bottom up within 5 to 8 years if not pressure-treated. Mulch decomposes about an inch per year, requiring annual top-ups. Gravel compacts 15 to 20 percent when you run a plate compactor over it, so you need to order more loose volume than the finished depth suggests. These environmental factors are built into the waste percentages and overage recommendations on every tool.</p>
    <h2>Hardscape: deck, fence, and patio</h2>
    <p>These three projects share a common foundation: concrete footings. Every deck post, fence post, and patio edge restraint sits on or in concrete that extends below the frost line. The depth of that frost line varies from 18 inches in the South to 48 inches in northern Minnesota. This single variable changes the concrete quantity by 2 to 3 times for the same project.</p>
    <p>The <Link href="/deck-calculator" className="text-accent hover:underline">deck calculator</Link> estimates decking boards, joists, beams, posts, and concrete footings from your deck dimensions and material choice. The <Link href="/fence-calculator" className="text-accent hover:underline">fence calculator</Link> does the same for posts, rails, pickets, and concrete by linear footage. The <Link href="/paver-calculator" className="text-accent hover:underline">paver calculator</Link> handles paver count, gravel base, bedding sand, polymeric joint sand, and edge restraint. All three have project planners that chain multiple calculations into a single material list: <Link href="/planner/build-a-deck" className="text-accent hover:underline">deck planner</Link>, <Link href="/planner/install-a-fence" className="text-accent hover:underline">fence planner</Link>, and <Link href="/planner/build-a-patio" className="text-accent hover:underline">patio planner</Link>.</p>
    <p>For cost breakdowns including DIY vs professional labor, regional pricing, and hidden costs, see the dedicated cost guides: <Link href="/cost-to-build-a-deck" className="text-accent hover:underline">cost to build a deck</Link>, <Link href="/cost-to-build-a-fence" className="text-accent hover:underline">cost to build a fence</Link>.</p>
    <h2>Softscape: mulch, topsoil, sod, and gravel</h2>
    <p>These four materials all use the same volume formula: area in square feet times depth in inches divided by 324 equals cubic yards. The number 324 is just 27 cubic feet per yard times 12 inches per foot. Despite sharing a formula, the four materials differ in density, cost, and how they are sold.</p>
    <p>The <Link href="/mulch-calculator" className="text-accent hover:underline">mulch calculator</Link> outputs cubic yards (how landscape supply yards quote bulk mulch) and bag count (how big-box stores sell it). The crossover point is about 2 cubic yards: below that, bags are practical; above that, bulk delivery saves money and hours of hauling. The <Link href="/gravel-calculator" className="text-accent hover:underline">gravel calculator</Link> outputs both cubic yards and tons, because gravel suppliers quote by weight while mulch suppliers quote by volume. One cubic yard of crushed stone weighs about 1.4 tons — confusing the two units results in ordering 30 percent too much or too little.</p>
    <p>The <Link href="/topsoil-calculator" className="text-accent hover:underline">topsoil calculator</Link> handles soil volume for garden beds and lawn prep, with guidance on screened vs amended vs fill-grade soil. The <Link href="/sod-calculator" className="text-accent hover:underline">sod calculator</Link> estimates pallets, rolls, or individual slabs by lawn area, with a 5 percent waste buffer for cuts at curves and edges.</p>
    <p>For projects that combine multiple materials (a patio with a gravel base, surrounded by new sod, with mulch in the garden beds), order everything from one landscape supply yard on the same delivery. Most yards split-load two or three materials on one truck, saving $100 or more in delivery fees.</p>
    <h2>Water: pool maintenance and rainwater collection</h2>
    <p>The <Link href="/pool-chlorine-calculator" className="text-accent hover:underline">pool chlorine calculator</Link> doses chemicals based on pool volume in gallons. Most pool owners estimate their volume incorrectly, which means every chemical dose is wrong — too much chlorine bleaches swimsuits and burns eyes, too little lets algae bloom. The calculator computes volume from your pool dimensions and gives exact doses for liquid bleach, tablets, and shock treatment.</p>
    <p>The <Link href="/rainwater-calculator" className="text-accent hover:underline">rainwater calculator</Link> sizes collection tanks from roof area and local rainfall. A 1,500 square foot roof in an area that gets 30 inches of annual rainfall collects roughly 28,000 gallons per year — enough to irrigate a large garden for the entire growing season without using municipal water.</p>
    <h2>Buying guides</h2>
    <p>For deck material selection, read the <Link href="/guides/composite-vs-pressure-treated-vs-cedar-deck" className="text-accent hover:underline">deck materials buying guide</Link> with 20-year total cost of ownership analysis comparing composite, pressure-treated pine, and cedar.</p>
  </div></section>
</article>); }
