import type { Metadata } from "next";
import Link from "next/link";
import { Figure, GuideByline, MethodologyNote, Scenario, GUIDE_SVG } from "@/components/GuideChrome";
import { ComparisonTable, Callout } from "@/components/GuideComponents";
export const metadata: Metadata = { title: "How much does it cost to pour concrete? (2026 prices)", description: "Concrete costs $6-16/ft² for a 4-inch slab installed. A 600 ft² driveway runs $5,000-10,000. Bags vs truck, stamped vs plain, full breakdown.", alternates: { canonical: "/cost-to-pour-concrete" } };
function PerSqFtSVG() { const types=[{label:"Plain slab (4\")",low:6,high:12},{label:"Stamped/colored",low:10,high:18},{label:"Exposed aggregate",low:8,high:15},{label:"Polished (interior)",low:4,high:10}]; return (<svg viewBox="0 0 680 190" width="100%" height="auto" role="img" aria-label="Concrete cost per sq ft: plain $6-12, stamped $10-18, polished $4-10."><text x="20" y="26" fontSize="13" fontWeight="600" fill={GUIDE_SVG.ink}>Installed cost per square foot by finish (2026)</text>{types.map((t,i)=>{const y=60+i*30;const xS=210+t.low*12;const w=(t.high-t.low)*12;return(<g key={t.label}><text x="200" y={y+14} textAnchor="end" fontSize="11" fontWeight="600" fill={GUIDE_SVG.ink}>{t.label}</text><rect x={xS} y={y} width={w} height="20" rx="3" fill={i===0?GUIDE_SVG.accent:GUIDE_SVG.slate} opacity="0.6"/><text x={xS-5} y={y+14} textAnchor="end" fontSize="10" fill={GUIDE_SVG.inkFaint}>${t.low}</text><text x={xS+w+5} y={y+14} fontSize="10" fill={GUIDE_SVG.inkFaint}>${t.high}/ft²</text></g>)})}</svg>); }
function BagsVsTruckSVG() { return (<svg viewBox="0 0 680 130" width="100%" height="auto" role="img" aria-label="Bags vs ready-mix: crossover at 1.5 cubic yards. Below that, bags are practical. Above, order a truck."><text x="20" y="26" fontSize="13" fontWeight="600" fill={GUIDE_SVG.ink}>Bags vs ready-mix truck</text><rect x="60" y="50" width="240" height="55" rx="8" fill={GUIDE_SVG.slateSoft} stroke={GUIDE_SVG.slate} strokeWidth="1"/><text x="180" y="72" textAnchor="middle" fontSize="10" fontWeight="700" fill={GUIDE_SVG.slate}>BAGS (80 lb)</text><text x="180" y="92" textAnchor="middle" fontSize="11" fill={GUIDE_SVG.ink}>$5.50–7.50/bag · 0.6 ft³ each</text><rect x="380" y="50" width="240" height="55" rx="8" fill={GUIDE_SVG.accentSoft} stroke={GUIDE_SVG.accent} strokeWidth="1"/><text x="500" y="72" textAnchor="middle" fontSize="10" fontWeight="700" fill={GUIDE_SVG.accent}>READY-MIX TRUCK</text><text x="500" y="92" textAnchor="middle" fontSize="11" fill={GUIDE_SVG.ink}>$130–180/yd³ · min 1 yd³</text><text x="340" y="125" textAnchor="middle" fontSize="9" fill={GUIDE_SVG.inkFaint} fontStyle="italic">Crossover: ~1.5 cubic yards. Below: bags work. Above: truck saves hours and your back.</text></svg>); }
function ProjectCostSVG() { const projects=[{project:"Sidewalk (4×30 ft, 4\")",yd:"1.5 yd³",cost:"$800–1,800"},{project:"Patio (12×16 ft, 4\")",yd:"2.4 yd³",cost:"$1,500–3,500"},{project:"Driveway (20×30 ft, 4\")",yd:"7.4 yd³",cost:"$5,000–10,000"},{project:"Garage slab (24×24 ft, 5\")",yd:"8.9 yd³",cost:"$6,000–12,000"}]; const hY=65;const rH=28; return (<svg viewBox="0 0 680 210" width="100%" height="auto" role="img" aria-label="Concrete project costs: sidewalk $800-1,800, driveway $5,000-10,000."><text x="20" y="26" fontSize="13" fontWeight="600" fill={GUIDE_SVG.ink}>Common concrete projects (installed, 2026)</text><rect x="40" y={hY-18} width="600" height="26" rx="4" fill={GUIDE_SVG.bgWarm}/>{[{l:"Project",x:160},{l:"Concrete",x:370},{l:"Total installed",x:530}].map(h=>(<text key={h.l} x={h.x} y={hY-2} textAnchor="middle" fontSize="10" fontWeight="700" fill={GUIDE_SVG.inkMuted}>{h.l}</text>))}{projects.map((p,i)=>{const y=hY+10+i*rH;return(<g key={p.project}>{i%2===0&&<rect x="40" y={y-4} width="600" height={rH} fill={GUIDE_SVG.bgWarm} opacity="0.4"/>}<text x="160" y={y+14} textAnchor="middle" fontSize="10" fontWeight="600" fill={GUIDE_SVG.ink}>{p.project}</text><text x="370" y={y+14} textAnchor="middle" fontSize="10" fill={GUIDE_SVG.inkMuted}>{p.yd}</text><text x="530" y={y+14} textAnchor="middle" fontSize="10" fill={GUIDE_SVG.accent} fontWeight="600">{p.cost}</text></g>)})}</svg>); }
export default function CostToPourConcrete() { return (<article>
  <section className="container-wide pt-6 md:pt-8"><div className="bg-bg-warm rounded-xl p-8 md:p-10"><nav aria-label="Breadcrumb" className="text-[11px] uppercase tracking-[0.08em] text-ink-faint mb-3 font-semibold"><Link href="/" className="text-accent hover:text-accent-hover transition-colors">Home</Link><span className="mx-2">·</span><span>Cost guides</span></nav><h1 className="text-3xl md:text-5xl font-bold tracking-tighter leading-[1.05] mb-3 text-ink">How much does it cost to pour concrete?</h1><p className="text-base md:text-lg text-ink-muted max-w-2xl leading-relaxed">A plain 4-inch slab costs $6-12 per square foot installed. Stamped or colored runs $10-18. The first decision: bags or a truck.</p></div></section>
  <section className="container-content py-10 md:py-14"><div className="guide-prose">
    <GuideByline updated="April 20, 2026" reviewedAgainst="NRMCA pricing, RS Means, and regional concrete contractor data" />
    <h2>The bags-or-truck decision comes first</h2>
    <p>Below 1.5 cubic yards, mixing bags is practical. Tedious, but practical. Above that, a ready-mix truck saves hours of mixing and your lower back. A ready-mix truck delivers concrete at $130-180 per cubic yard with a 1-yard minimum. At that price, the concrete for a 600 square foot driveway (7.4 yards) costs about $1,100 in material. The <Link href="/concrete-calculator" className="text-accent hover:underline">concrete calculator</Link> tells you exactly how many yards your project needs so you know which side of the crossover you are on.</p>
    <Figure number={1} caption="Plain slab is the baseline at $6-12/ft². Decorative finishes (stamped, exposed aggregate) add 50-80% to the cost."><PerSqFtSVG /></Figure>
    <MethodologyNote><p>Ready-mix pricing from NRMCA (National Ready Mixed Concrete Association) regional surveys. Installed costs from RS Means 2026 residential concrete section and HomeGuide contractor databases.</p></MethodologyNote>
    <Figure number={2} caption="Below 1.5 cubic yards, bags work. Above that, a truck saves hours and produces better concrete (consistent mix, no cold joints)."><BagsVsTruckSVG /></Figure>
    <Figure number={3} caption="Material is 20-30% of installed cost. Labor, grading, forming, finishing, and curing are the rest."><ProjectCostSVG /></Figure>
    <Scenario location="Phoenix, AZ">A homeowner poured a 12×16 patio slab (192 ft², 4 inches thick, 2.4 cubic yards). Ready-mix delivery: $350 (2.4 yd³ × $145). Gravel base, rebar, forming lumber: $280. He formed and placed it himself with two helpers. Total material: $630. A contractor quoted $2,200 for the same slab. His DIY savings: $1,570. The trade-off: a full Saturday of hard physical labor in Arizona heat and a finish that a pro would have made smoother.</Scenario>
    <ComparisonTable columns={[{title:"DIY"},{title:"Professional"}]} rows={[{label:"Concrete (600 ft² slab)",values:["$1,100","$1,100"]},{label:"Gravel base + rebar",values:["$400–600","Included"]},{label:"Forms + stakes",values:["$100–200","Included"]},{label:"Finishing tools rental",values:["$75–150","Own equipment"]},{label:"Labor",values:["$0 (brutal day)","$2,500–5,000"]},{label:"Total",values:[<strong key="d">$1,675–2,050</strong>,<strong key="p">$5,000–10,000</strong>]}]} caption="DIY concrete saves 60-70% but requires helpers (you cannot pour a driveway alone), finishing skill, and physical endurance. Concrete waits for nobody." />
    <Callout label="You cannot undo a pour">Concrete begins setting within 90 minutes. Once the truck arrives, the clock starts. Forming, grading, and rebar placement must be complete before the truck backs up. If you are not ready, you pay a standby fee ($2-3 per minute) or the driver dumps the load where you are not prepared. This is not a project you can figure out as you go.</Callout>
    <p>For exact quantities, use the <Link href="/concrete-calculator" className="text-accent hover:underline">concrete calculator</Link>. For reinforcement, the <Link href="/rebar-calculator" className="text-accent hover:underline">rebar calculator</Link> sizes the grid.</p>
  </div></section>
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({"@context":"https://schema.org","@type":"Article",headline:"How much does it cost to pour concrete? (2026)",datePublished:"2026-04-16",dateModified:"2026-04-20",author:{"@type":"Person",name:"Ash K.",url:"https://www.tallyard.com/about"},publisher:{"@type":"Organization",name:"Tallyard",url:"https://www.tallyard.com"},mainEntityOfPage:"https://www.tallyard.com/cost-to-pour-concrete"})}}/>
</article>); }
