import type { Metadata } from "next";
import Link from "next/link";
import { Figure, GuideByline, MethodologyNote, Scenario, GUIDE_SVG } from "@/components/GuideChrome";
import { ComparisonTable, Callout } from "@/components/GuideComponents";
export const metadata: Metadata = { title: "How much does it cost to paint a house? (2026 prices)", description: "Interior: $2-6/ft². Exterior: $3-8/ft². A 2,000 ft² home costs $1,500-4,000 interior or $3,000-8,000 exterior. Full breakdown.", alternates: { canonical: "/cost-to-paint-a-house" } };
function IntVsExtSVG() { return (<svg viewBox="0 0 680 130" width="100%" height="auto" role="img" aria-label="Interior paint: $2-6/ft². Exterior: $3-8/ft²."><text x="20" y="26" fontSize="13" fontWeight="600" fill={GUIDE_SVG.ink}>Interior vs exterior painting cost (per ft², professional)</text><rect x="60" y="50" width="250" height="55" rx="8" fill={GUIDE_SVG.accentSoft} stroke={GUIDE_SVG.accent} strokeWidth="1"/><text x="185" y="72" textAnchor="middle" fontSize="11" fontWeight="700" fill={GUIDE_SVG.accent}>INTERIOR</text><text x="185" y="92" textAnchor="middle" fontSize="16" fontWeight="700" fill={GUIDE_SVG.ink}>$2–6/ft²</text><rect x="370" y="50" width="250" height="55" rx="8" fill={GUIDE_SVG.slateSoft} stroke={GUIDE_SVG.slate} strokeWidth="1"/><text x="495" y="72" textAnchor="middle" fontSize="11" fontWeight="700" fill={GUIDE_SVG.slate}>EXTERIOR</text><text x="495" y="92" textAnchor="middle" fontSize="16" fontWeight="700" fill={GUIDE_SVG.ink}>$3–8/ft²</text></svg>); }
function RoomCostSVG() { const rooms=[{label:"Bedroom (150 ft²)",diy:"$75–150",pro:"$300–600"},{label:"Living room (300 ft²)",diy:"$150–250",pro:"$500–1,000"},{label:"Kitchen (200 ft² walls)",diy:"$100–200",pro:"$400–800"},{label:"Whole house interior",diy:"$500–1,500",pro:"$2,000–5,000"}]; const hY=65;const rH=28; return (<svg viewBox="0 0 680 210" width="100%" height="auto" role="img" aria-label="Room paint cost: bedroom $300-600 pro, whole house $2,000-5,000."><text x="20" y="26" fontSize="13" fontWeight="600" fill={GUIDE_SVG.ink}>Interior painting cost by room</text><rect x="50" y={hY-18} width="580" height="26" rx="4" fill={GUIDE_SVG.bgWarm}/>{[{l:"Room",x:160},{l:"DIY",x:360},{l:"Professional",x:520}].map(h=>(<text key={h.l} x={h.x} y={hY-2} textAnchor="middle" fontSize="10" fontWeight="700" fill={GUIDE_SVG.inkMuted}>{h.l}</text>))}{rooms.map((r,i)=>{const y=hY+10+i*rH;return(<g key={r.label}>{i%2===0&&<rect x="50" y={y-4} width="580" height={rH} fill={GUIDE_SVG.bgWarm} opacity="0.4"/>}<text x="160" y={y+14} textAnchor="middle" fontSize="11" fontWeight="600" fill={GUIDE_SVG.ink}>{r.label}</text><text x="360" y={y+14} textAnchor="middle" fontSize="11" fill={GUIDE_SVG.inkMuted}>{r.diy}</text><text x="520" y={y+14} textAnchor="middle" fontSize="11" fill={GUIDE_SVG.accent} fontWeight="600">{r.pro}</text></g>)})}</svg>); }
function ExteriorBreakdownSVG() { return (<svg viewBox="0 0 680 160" width="100%" height="auto" role="img" aria-label="Exterior paint cost breakdown: paint 25%, prep/scrape 30%, labor 35%, equipment 10%."><text x="20" y="26" fontSize="13" fontWeight="600" fill={GUIDE_SVG.ink}>Where exterior paint money goes</text>{[{label:"Paint + primer",pct:25,color:GUIDE_SVG.accent},{label:"Prep (scrape, caulk, prime)",pct:30,color:GUIDE_SVG.inkMuted},{label:"Labor (application)",pct:35,color:GUIDE_SVG.slate},{label:"Equipment (ladders, sprayer)",pct:10,color:GUIDE_SVG.inkFaint}].map((item,i)=>{const y=55+i*24;return(<g key={item.label}><rect x="240" y={y} width={item.pct*8} height="16" rx="3" fill={item.color} opacity="0.6"/><text x="230" y={y+12} textAnchor="end" fontSize="10" fontWeight="600" fill={GUIDE_SVG.ink}>{item.label}</text><text x={248+item.pct*8} y={y+12} fontSize="10" fontWeight="600" fill={GUIDE_SVG.ink}>{item.pct}%</text></g>)})}</svg>); }
function PaintGradeSVG() { return (<svg viewBox="0 0 680 120" width="100%" height="auto" role="img" aria-label="Paint quality: builder grade $20-30/gal, mid-range $35-55, premium $55-80."><text x="20" y="26" fontSize="13" fontWeight="600" fill={GUIDE_SVG.ink}>Paint quality tiers</text>{[{grade:"Builder / economy",cost:"$20–30/gal",cover:"300 ft²/gal",x:50},{grade:"Mid-range (Behr, Valspar)",cost:"$35–55/gal",cover:"350 ft²/gal",x:260},{grade:"Premium (BM, SW Duration)",cost:"$55–80/gal",cover:"400 ft²/gal",x:470}].map(g=>(<g key={g.grade}><rect x={g.x} y="55" width="180" height="45" rx="6" fill={GUIDE_SVG.slateSoft} stroke={GUIDE_SVG.slate} strokeWidth="1"/><text x={g.x+90} y="72" textAnchor="middle" fontSize="9" fontWeight="600" fill={GUIDE_SVG.ink}>{g.grade}</text><text x={g.x+90} y="88" textAnchor="middle" fontSize="11" fontWeight="700" fill={GUIDE_SVG.accent}>{g.cost}</text></g>))}</svg>); }
export default function CostToPaintHouse() { return (<article>
  <section className="container-wide pt-6 md:pt-8"><div className="bg-bg-warm rounded-xl p-8 md:p-10"><nav aria-label="Breadcrumb" className="text-[11px] uppercase tracking-[0.08em] text-ink-faint mb-3 font-semibold"><Link href="/" className="text-accent hover:text-accent-hover transition-colors">Home</Link><span className="mx-2">·</span><span>Cost guides</span></nav><h1 className="text-3xl md:text-5xl font-bold tracking-tighter leading-[1.05] mb-3 text-ink">How much does it cost to paint a house?</h1><p className="text-base md:text-lg text-ink-muted max-w-2xl leading-relaxed">Interior and exterior are different projects with different costs. Interior runs $2-6 per square foot. Exterior runs $3-8. The prep is half the bill either way.</p></div></section>
  <section className="container-content py-10 md:py-14"><div className="guide-prose">
    <GuideByline updated="April 20, 2026" reviewedAgainst="PCA (Painting Contractors of America) cost surveys and manufacturer coverage rates" />
    <h2>Interior and exterior are two completely different jobs</h2>
    <p>Interior painting is mostly cutting in and rolling — low setup, moderate skill, manageable for a DIYer. Exterior painting involves ladders, scaffolding, power washing, scraping, caulking, priming bare wood, and weather windows that limit when you can work. The prep on an exterior job typically takes longer than the painting itself. That is why exterior costs 40 to 80 percent more per square foot than interior, even though the paint is the same price.</p>
    <Figure number={1} caption="Interior is cheaper per square foot because access is easier, prep is lighter, and weather is not a factor."><IntVsExtSVG /></Figure>
    <MethodologyNote><p>Interior costs from PCA residential painting surveys. Exterior costs from HomeGuide and Angi 2025-2026 contractor databases. Coverage rates from Benjamin Moore, Sherwin-Williams, and Behr product data sheets.</p></MethodologyNote>
    <h2>Interior: cost by room</h2>
    <Figure number={2} caption="DIY paint costs $75-250 per room in materials. Professional labor adds $200-500 per room depending on size and prep needed."><RoomCostSVG /></Figure>
    <p>DIY interior painting is the highest-ROI skill a homeowner can learn. Materials for a bedroom cost $75 to $150 (one gallon of paint, roller, tray, tape). A professional charges $300 to $600 for the same room. The only tool investment is a good angled brush ($15), a roller frame ($8), and covers ($5 each). That $28 kit pays for itself on the first room. The <Link href="/paint-calculator" className="text-accent hover:underline">paint calculator</Link> tells you exactly how many gallons you need.</p>
    <h2>Exterior: prep is where the money goes</h2>
    <Figure number={3} caption="Only 25% of an exterior paint job cost is the paint itself. Prep (scraping, caulking, priming) accounts for 30% and is the most labor-intensive phase."><ExteriorBreakdownSVG /></Figure>
    <Scenario location="Minneapolis, MN">A homeowner got two bids to paint a 2,200 ft² two-story Colonial. Bid A: $5,800 (includes power wash, scrape loose paint, spot-prime, two coats). Bid B: $4,200 (power wash and two coats, no scraping). He picked Bid B to save $1,600. Within two years the new paint was peeling in every area where old paint had been loose underneath. Repainting those areas cost $2,500. The prep the cheaper bid skipped is what makes paint stick.</Scenario>
    <h2>Paint quality matters more than most people think</h2>
    <Figure number={4} caption="Premium paint costs twice as much per gallon but covers better (fewer coats), lasts longer (10-15 years vs 5-7), and is easier to apply. The per-gallon premium is small relative to total project cost."><PaintGradeSVG /></Figure>
    <ComparisonTable columns={[{title:"Economy paint"},{title:"Premium paint"}]} rows={[{label:"Cost/gallon",values:["$20–30","$55–80"]},{label:"Coverage",values:["300 ft²/gal","400 ft²/gal"]},{label:"Coats needed",values:["Often 3","Usually 2"]},{label:"Durability",values:["5–7 years","10–15 years"]},{label:"Cost per year of life",values:["$4–6/gal/yr","$4–8/gal/yr"]}]} caption="Premium paint costs more per gallon but covers more per gallon, needs fewer coats, and lasts twice as long. Per year of life, the cost difference is minimal." />
    <Callout label="The primer question">Primer is needed on bare drywall, bare wood, stains, and drastic color changes. It is NOT needed for same-color repaints over existing paint in good condition. Skipping unnecessary primer saves $200-400 on a whole-house interior. Adding necessary primer prevents $1,000+ in repainting when the topcoat fails to adhere.</Callout>
    <p>Use the <Link href="/paint-calculator" className="text-accent hover:underline">paint calculator</Link> for exact gallon counts. The <Link href="/planner/paint-a-room" className="text-accent hover:underline">paint project planner</Link> adds primer, supplies, and ceiling paint to the material list.</p>
  </div></section>
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({"@context":"https://schema.org","@type":"Article",headline:"How much does it cost to paint a house? (2026)",datePublished:"2026-04-11",dateModified:"2026-04-20",author:{"@type":"Person",name:"Ash K.",url:"https://www.tallyard.com/about"},publisher:{"@type":"Organization",name:"Tallyard",url:"https://www.tallyard.com"},mainEntityOfPage:"https://www.tallyard.com/cost-to-paint-a-house"})}}/>
</article>); }
